name: 'Export a key-value pair JSON to env variables'
description: 'Utility action that exports JSON in key-value pair format to environment variables'
author: 'Raphael Neumann @Raphaelneumann'
inputs:
  json_envs:
    required: true
    description: JSON in ey-value pair format (like secrets or vars) to be exported to enviroment variables'
  prefix:
    required: false
    description: 'Prefix to add to all varibles, e.g.: VARS_'
  include:
    required: false
    description: 'Comma-separated list of keys to export'
  exclude:
    required: false
    description: 'Comma-separated list of key to skip exporting'
  convert:
    required: false
    description: 'Converts key name to a specific string format'
  convert_prefix:
    required: false
    description: 'Include prefix (or not) on conversion. True by default'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: orange
